### ISSUE TITLE
카카오페이 API 내역 데이터베이스 구축

### ISSUE THREAD

**Issue by ghdcksgml1** [ghdcksgml1/swhackathon-backend#20]
* [ ] 결제내역 도메인 설계 (결과체크)
  * [ ] 결제완료
  * [ ] 취소되면, 상태변경시키게

**Comment by ITKOO** [comment]
토스 페이먼츠로 변경되었고,
완료된 기능이므로 이슈 완료 처리합니다
항상 감솨합니다 최고
