### ISSUE TITLE
소셜 로그인 구현

### ISSUE THREAD

**Issue by ji-hyeon97** [ghdcksgml1/swhackathon-backend#3]
나중에 더 알아보아야 할 부분들 (까먹지 않도록 ,,)
1. postman에서 oauth 2.0을 어떻게 다루는지

<img width="500" alt="스크린샷 2022-07-20 오후 4 32 46" src="https://user-images.githubusercontent.com/79920930/179924582-038f6bd6-1054-478b-9326-9c6a4c4e37d5.png">

2. 네이버 로그인 할때 여기에 사람들 아이디를 등록해주어야 한다 ?!!

<img width="500" alt="스크린샷 2022-07-20 오후 4 39 29" src="https://user-images.githubusercontent.com/79920930/179925138-34f3ed82-691a-4801-aca2-a380d357e3c8.png">
친구 걸로 가입해보려다가 에러 생겨서 확인해 보니 친구 아이디를 내 애플리케이션에 등록을 해야됨 ....

**Comment by ITKOO** [comment]
이미 완료된 기능이므로 이슈 완료 처리합니다
