### ISSUE TITLE
(프론트 요청) 시간대별 오더 목록 조회 API에 필드 값 추가 /api/order/time/{timeIndex}

### ISSUE THREAD

**Issue by ITKOO** [ghdcksgml1/swhackathon-backend#31]
시간대로 오더 목록을 조회하는 아래 api에
GET http://api-eatda.wintersoft.kr/api/order/time/{timeIndex}

각 오더 별 상세 정보를 넣어주실 수 있을까요?
해당 api는 인덱스 페이지에서 호출할 예정여서
아래 정보가 위 api에 있으면 좋겠습니다!

[가게 명, 가게사진, 주문 최소금액, 딜 성공 금액, 현재 주문금액, 배달 수령지]

**Comment by ghdcksgml1** [comment]
완료 👍

**Comment by ITKOO** [comment]
확인했습니다~ 잘 작동합니다 최고!
이슈 닫겠습니다!
