### ISSUE TITLE
(프론트 요청) 회원가입시 핸드폰 번호 필드 추가 및  유효성 체크

### ISSUE THREAD

**Issue by ITKOO** [ghdcksgml1/swhackathon-backend#34]
1. 회원가입할 때 핸드폰 번호를 입력받는 필드를 추가할 예정입니다
DB 에 필드 추가 부탁드립니다!

2. 회원가입 시 핸드폰번호에 대한 유효성 체크 추가 부탁드립니다
이미 등록된 핸드폰 번호일경우! 기존처럼 에러 코드를 내려주세요~

**Comment by ghdcksgml1** [comment]
추가 완료했습니다.

**Comment by ITKOO** [comment]
완료된 기능이므로 이슈 완료 처리합니다
