### ISSUE TITLE
(프론트 요청) 주문목록 조회 api에 필드 추가 및 정렬 순서 변경

### ISSUE THREAD

**Issue by ITKOO** [ghdcksgml1/swhackathon-backend#35]
유저의 모든 주문 목록을 조회하는 api에서 GET /api/orderDetail/userOrderDetail/
1. 아래 필드를 추가해주실수 있을까요?
주문 히스토리 페이지에서 노출시 아래  정보가 필요합니다~
- 주문시간
- 주문시간대(오늘점심/내일점심..)
- 주문장소(진리/웅비..),
- 주문상태(대기/배달/완료)

![스크린샷 2022-10-20 오전 6 50 35](https://user-images.githubusercontent.com/31758135/196811574-ab4a9216-ba8c-4329-a77c-4b7668f9a1b9.png)

2. 현재 히스토리 정렬이 과거 내역부터 내려오고 있습니다
최신순으로 정렬해서 내려주실 수 있을까요~?

항상 감사합니닷 ㅎㅎ

**Comment by ghdcksgml1** [comment]
완료했습니당

**Comment by ITKOO** [comment]
완료된 기능이므로 이슈 완료 처리합니다
항상 감솨합니다 최고
