### ISSUE TITLE
옵션 타이틀 테이블에 다중선택 여부 컬럼 생성

### ISSUE THREAD

**Issue by ITKOO** [ghdcksgml1/swhackathon-backend#40]
옵션 타이틀별로 다중선택이 가능한 옵션인지의 여부가
필요합니다

해당 컬럼 추가 부탁드립니다
ex) 맵기는 1개만 선택가능, 추가토핑은 여러개 선택 가능

**Comment by ghdcksgml1** [comment]
### 아래 보이는 multipleCheck가 true면 다중선택가능, false일 경우 1개만 선택가능으로 해주시면 될것같아요.

<img width="532" alt="스크린샷 2022-11-27 오전 11 59 42" src="https://user-images.githubusercontent.com/79779676/204117265-d90a4908-3740-471e-a454-9e37117ec666.png">

**Comment by ITKOO** [comment]
작동 잘 되는 것 확인했습니다 감사합니다
이슈 닫겠습니다(+ 프론트 연동도 완료)
